#pragma once

#include "../../NT/MinDef.h"

#define UXTHEME_ATOM_SUBIDLIST  ((ATOM)0xA910) // #43280
#define UXTHEME_ATOM_SUBAPPNAME ((ATOM)0xA911) // #43281

#define UXTHEME_ATOM_DLGTEXTURE_NT5 ((ATOM)0xA917) // #43287
#define UXTHEME_ATOM_DLGTEXTURE_NT6 ((ATOM)0xA916) // #43286
#if NTDDI_VERSION < NTDDI_WIN6
#define UXTHEME_ATOM_DLGTEXTURE UXTHEME_ATOM_DLGTEXTURE_NT5
#else
#define UXTHEME_ATOM_DLGTEXTURE UXTHEME_ATOM_DLGTEXTURE_NT6
#endif
