#define RELEASE_VER_MAIN    1
#define RELEASE_VER_SUB     5
#define RELEASE_VER_FIX     1

#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)

#define RELEASE_VER_STR     TOSTRING(RELEASE_VER_MAIN) "." TOSTRING(RELEASE_VER_SUB) "." TOSTRING(RELEASE_VER_FIX)
