#ifndef CHROME_PLUS_SRC_VERSION_H_
#define CHROME_PLUS_SRC_VERSION_H_

#define RELEASE_VER_MAIN 1
#define RELEASE_VER_SUB 12
#define RELEASE_VER_FIX 1

#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)

#define RELEASE_VER_STR      \
  TOSTRING(RELEASE_VER_MAIN) \
  "." TOSTRING(RELEASE_VER_SUB) "." TOSTRING(RELEASE_VER_FIX)

#endif  // CHROME_PLUS_SRC_VERSION_H_
