#pragma once

#include "../MinDef.h"
#include "../../NDK.Ext.h"

#pragma region Well-known SIDs

/*
 * See also:
 *   https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/81d92bba-d22b-4a8c-908a-554ab29148ab
 *   https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids
 *   https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers#well-known-sids
 */

/* SID_X, X = SubAuthorityCount */
typedef DEFINE_ANYSIZE_STRUCT(SID_2, SID, DWORD, 2);
typedef DEFINE_ANYSIZE_STRUCT(SID_3, SID, DWORD, 3);
typedef DEFINE_ANYSIZE_STRUCT(SID_4, SID, DWORD, 4);
typedef DEFINE_ANYSIZE_STRUCT(SID_5, SID, DWORD, 5);
typedef DEFINE_ANYSIZE_STRUCT(SID_6, SID, DWORD, 6);
typedef DEFINE_ANYSIZE_STRUCT(SID_7, SID, DWORD, 7);

// S-1-0-0
#define SID_NULL { SID_REVISION, 1, SECURITY_NULL_SID_AUTHORITY, { SECURITY_NULL_RID } }
// S-1-1-0
#define SID_EVERYONE { SID_REVISION, 1, SECURITY_WORLD_SID_AUTHORITY, { SECURITY_WORLD_RID } }
#define SID_WORLD SID_EVERYONE
// S-1-2-0
#define SID_LOCAL { SID_REVISION, 1, SECURITY_LOCAL_SID_AUTHORITY, { SECURITY_LOCAL_RID } }
// S-1-2-1
#define SID_CONSOLE_LOGON { SID_REVISION, 1, SECURITY_LOCAL_SID_AUTHORITY, { SECURITY_LOCAL_LOGON_RID } }
// S-1-3-0
#define SID_CREATOR_OWNER { SID_REVISION, 1, SECURITY_CREATOR_SID_AUTHORITY, { SECURITY_CREATOR_OWNER_RID } }
// S-1-3-1
#define SID_CREATOR_GROUP { SID_REVISION, 1, SECURITY_CREATOR_SID_AUTHORITY, { SECURITY_CREATOR_GROUP_RID } }
// S-1-3-2
#define SID_OWNER_SERVER { SID_REVISION, 1, SECURITY_CREATOR_SID_AUTHORITY, { SECURITY_CREATOR_OWNER_SERVER_RID } }
// S-1-3-3
#define SID_GROUP_SERVER { SID_REVISION, 1, SECURITY_CREATOR_SID_AUTHORITY, { SECURITY_CREATOR_GROUP_SERVER_RID } }
// S-1-3-4
#define SID_OWNER_RIGHTS { SID_REVISION, 1, SECURITY_CREATOR_SID_AUTHORITY, { SECURITY_CREATOR_OWNER_RIGHTS_RID } }

/* NT Authority */

// S-1-5-1
#define SID_DIALUP { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_DIALUP_RID } }
// S-1-5-2
#define SID_NETWORK { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_NETWORK_RID } }
// S-1-5-3
#define SID_BATCH { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_BATCH_RID } }
// S-1-5-4
#define SID_INTERACTIVE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_INTERACTIVE_RID } }
// S-1-5-6
#define SID_SERVICE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_SERVICE_RID } }
// S-1-5-7
#define SID_ANONYMOUS { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_ANONYMOUS_LOGON_RID } }
// S-1-5-8
#define SID_PROXY { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_PROXY_RID } }
// S-1-5-9
#define SID_ENTERPRISE_DOMAIN_CONTROLLERS { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_ENTERPRISE_CONTROLLERS_RID } }
// S-1-5-9, same as SID_ENTERPRISE_DOMAIN_CONTROLLERS 
#define SID_SERVER_LOGON { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_SERVER_LOGON_RID } }
// S-1-5-10
#define SID_PRINCIPAL_SELF { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_PRINCIPAL_SELF_RID } }
// S-1-5-11
#define SID_AUTHENTICATED_USERS { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_AUTHENTICATED_USER_RID } }
// S-1-5-12
#define SID_RESTRICTED_CODE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_RESTRICTED_CODE_RID } }
// S-1-5-13
#define SID_TERMINAL_SERVER_USER { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_TERMINAL_SERVER_RID } }
// S-1-5-14
#define SID_REMOTE_INTERACTIVE_LOGON { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_REMOTE_LOGON_RID } }
// S-1-5-15
#define SID_THIS_ORGANIZATION { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_THIS_ORGANIZATION_RID } }
// S-1-5-17
#define SID_IUSER { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_IUSER_RID } }
// S-1-5-18
#define SID_LOCAL_SYSTEM { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_LOCAL_SYSTEM_RID } }
// S-1-5-19
#define SID_LOCAL_SERVICE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_LOCAL_SERVICE_RID } }
// S-1-5-20
#define SID_NETWORK_SERVICE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_NETWORK_SERVICE_RID } }
// S-1-5-21-0-0-0-496
#define SID_COMPOUNDED_AUTHENTICATION { SID_REVISION, 5, SECURITY_NT_AUTHORITY, { SECURITY_NT_NON_UNIQUE }, { 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_IS_COMPOUNDED } }
// S-1-5-21-0-0-0-497
#define SID_CLAIMS_VALID { SID_REVISION, 5, SECURITY_NT_AUTHORITY, { SECURITY_NT_NON_UNIQUE }, { 0, 0, 0, DOMAIN_GROUP_RID_AUTHORIZATION_DATA_CONTAINS_CLAIMS } }

/* Built-in Groups */

// S-1-5-32-544
#define SID_BUILTIN_ADMINISTRATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_ADMINS } }
// S-1-5-32-545
#define SID_BUILTIN_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_USERS } }
// S-1-5-32-546
#define SID_BUILTIN_GUESTS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_GUESTS } }
// S-1-5-32-547
#define SID_POWER_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_POWER_USERS } }
// S-1-5-32-548
#define SID_ACCOUNT_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_ACCOUNT_OPS } }
// S-1-5-32-549
#define SID_SERVER_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_SYSTEM_OPS } }
// S-1-5-32-550
#define SID_PRINTER_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_PRINT_OPS } }
// S-1-5-32-551
#define SID_BACKUP_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_BACKUP_OPS } }
// S-1-5-32-552
#define SID_REPLICATOR { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_REPLICATOR } }
// S-1-5-32-554
#define SID_ALIAS_PREW2KCOMPACC { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_PREW2KCOMPACCESS } }
// S-1-5-32-555
#define SID_REMOTE_DESKTOP { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_REMOTE_DESKTOP_USERS } }
// S-1-5-32-556
#define SID_NETWORK_CONFIGURATION_OPS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_NETWORK_CONFIGURATION_OPS } }
// S-1-5-32-557
#define SID_INCOMING_FOREST_TRUST_BUILDERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_INCOMING_FOREST_TRUST_BUILDERS } }
// S-1-5-32-558
#define SID_PERFMON_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_MONITORING_USERS } }
// S-1-5-32-559
#define SID_PERFLOG_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_LOGGING_USERS } }
// S-1-5-32-560
#define SID_WINDOWS_AUTHORIZATION_ACCESS_GROUP { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_AUTHORIZATIONACCESS } }
// S-1-5-32-561
#define SID_TERMINAL_SERVER_LICENSE_SERVERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_TS_LICENSE_SERVERS } }
// S-1-5-32-562
#define SID_DISTRIBUTED_COM_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_DCOM_USERS } }
// S-1-5-32-568
#define SID_IIS_IUSRS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_IUSERS } }
// S-1-5-32-569
#define SID_CRYPTOGRAPHIC_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_CRYPTO_OPERATORS } }
// S-1-5-32-571
#define SID_CACHEABLE_PRINCIPALS_GROUP { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_CACHEABLE_PRINCIPALS_GROUP } }
// S-1-5-32-572
#define SID_NON_CACHEABLE_PRINCIPALS_GROUP { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_NON_CACHEABLE_PRINCIPALS_GROUP } }
// S-1-5-32-573
#define SID_EVENT_LOG_READERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_EVENT_LOG_READERS_GROUP } }
// S-1-5-32-574
#define SID_CERTIFICATE_SERVICE_DCOM_ACCESS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_CERTSVC_DCOM_ACCESS_GROUP } }
// S-1-5-32-575
#define SID_RDS_REMOTE_ACCESS_SERVERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_RDS_REMOTE_ACCESS_SERVERS } }
// S-1-5-32-576
#define SID_RDS_ENDPOINT_SERVERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_RDS_ENDPOINT_SERVERS } }
// S-1-5-32-577
#define SID_RDS_MANAGEMENT_SERVERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_RDS_MANAGEMENT_SERVERS } }
// S-1-5-32-578
#define SID_HYPER_V_ADMINS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_HYPER_V_ADMINS } }
// S-1-5-32-579
#define SID_ACCESS_CONTROL_ASSISTANCE_OPS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_ACCESS_CONTROL_ASSISTANCE_OPS } }
// S-1-5-32-580
#define SID_REMOTE_MANAGEMENT_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_REMOTE_MANAGEMENT_USERS } }
// S-1-5-32-581
#define SID_DEFAULT_ACCOUNT { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_DEFAULT_ACCOUNT } }
// S-1-5-32-582
#define SID_STORAGE_REPLICA_ADMINS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_STORAGE_REPLICA_ADMINS } }
// S-1-5-32-583
#define SID_STORAGE_DEVICE_OWNERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_DEVICE_OWNERS } }
// S-1-5-32-584
#define SID_STORAGE_USER_MODE_HARDWARE_OPERATORS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_USER_MODE_HARDWARE_OPERATORS } }
// S-1-5-32-585
#define SID_STORAGE_OPENSSH_USERS { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_BUILTIN_DOMAIN_RID } }, { DOMAIN_ALIAS_RID_OPENSSH_USERS } }

// S-1-5-33
#define SID_WRITE_RESTRICTED_CODE { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_WRITE_RESTRICTED_CODE_RID } }
// S-1-5-64-10
#define SID_NTLM_AUTHENTICATION { { SID_REVISION, SECURITY_PACKAGE_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_PACKAGE_BASE_RID } }, { SECURITY_PACKAGE_NTLM_RID } }
// S-1-5-64-14
#define SID_SCHANNEL_AUTHENTICATION { { SID_REVISION, SECURITY_PACKAGE_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_PACKAGE_BASE_RID } }, { SECURITY_PACKAGE_SCHANNEL_RID } }
// S-1-5-64-21
#define SID_DIGEST_AUTHENTICATION { { SID_REVISION, SECURITY_PACKAGE_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_PACKAGE_BASE_RID } }, { SECURITY_PACKAGE_DIGEST_RID } }
// S-1-5-65-1
#define SID_THIS_ORGANIZATION_CERTIFICATE { { SID_REVISION, SECURITY_CRED_TYPE_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_CRED_TYPE_BASE_RID } }, { SECURITY_CRED_TYPE_THIS_ORG_CERT_RID } }

/* NT Service */

// S-1-5-80-0
#define SID_NT_SERVICE_ALL_SERVICES { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_SERVICE_ID_BASE_RID } }, { 0 } }
// S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464
#define SID_TRUSTED_INSTALLER { { SID_REVISION, SECURITY_SERVICE_ID_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_SERVICE_ID_BASE_RID } }, { SECURITY_TRUSTED_INSTALLER_RID1, SECURITY_TRUSTED_INSTALLER_RID2, SECURITY_TRUSTED_INSTALLER_RID3, SECURITY_TRUSTED_INSTALLER_RID4, SECURITY_TRUSTED_INSTALLER_RID5 } }
// S-1-5-83-0
#define SID_NT_VIRTUAL_MACHINE_VIRTUAL_MACHINES { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_VIRTUALSERVER_ID_BASE_RID } }, { 0 } }
// S-1-5-84-0-0-0-0-0
#define SID_USER_MODE_DRIVERS { { SID_REVISION, SECURITY_USERMODEDRIVERHOST_ID_RID_COUNT, SECURITY_NT_AUTHORITY, { SECURITY_USERMODEDRIVERHOST_ID_BASE_RID } }, { 0, 0, 0, 0, 0 } }
// S-1-5-90-0
#define SID_WINDOWS_MANAGER_WINDOWS_MANAGER_GROUP { { SID_REVISION, 2, SECURITY_NT_AUTHORITY, { SECURITY_WINDOW_MANAGER_BASE_RID } }, { 0 } }

// S-1-5-113
#define SID_LOCAL_ACCOUNT { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_LOCAL_ACCOUNT_RID } }
// S-1-5-114
#define SID_LOCAL_ACCOUNT_AND_MEMBER_OF_ADMINISTRATORS_GROUP { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_LOCAL_ACCOUNT_AND_ADMIN_RID } }
// S-1-5-1000
#define SID_OTHER_ORGANIZATION { SID_REVISION, 1, SECURITY_NT_AUTHORITY, { SECURITY_OTHER_ORGANIZATION_RID } }
// S-1-15-2-1
#define SID_ALL_APP_PACKAGES { { SID_REVISION, SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT, SECURITY_APP_PACKAGE_AUTHORITY, { SECURITY_APP_PACKAGE_BASE_RID } }, { SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE } }

/* Mandatory Labels */

// S-1-16-0
#define SID_ML_UNTRUSTED { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_UNTRUSTED_RID } }
// S-1-16-4096
#define SID_ML_LOW { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_LOW_RID } }
// S-1-16-8192
#define SID_ML_MEDIUM { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_MEDIUM_RID } }
// S-1-16-8448
#define SID_ML_MEDIUM_PLUS { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_MEDIUM_PLUS_RID } }
// S-1-16-12288
#define SID_ML_HIGH { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_HIGH_RID } }
// S-1-16-16384
#define SID_ML_SYSTEM { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_SYSTEM_RID } }
// S-1-16-20480
#define SID_ML_PROTECTED_PROCESS { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_PROTECTED_PROCESS_RID } }
// S-1-16-28672
#define SID_ML_SECURE_PROCESS { SID_REVISION, 1, SECURITY_MANDATORY_LABEL_AUTHORITY, { SECURITY_MANDATORY_SECURE_PROCESS_RID } }

/* Authentication Authority */

// S-1-18-1
#define SID_AUTHENTICATION_AUTHORITY_ASSERTED_IDENTITY { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_AUTHORITY_ASSERTED_RID } }
// S-1-18-2
#define SID_SERVICE_ASSERTED_IDENTITY { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_SERVICE_ASSERTED_RID } }
// S-1-18-3
#define SID_FRESH_PUBLIC_KEY_IDENTITY { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_FRESH_KEY_AUTH_RID } }
// S-1-18-4
#define SID_KEY_TRUST_IDENTITY { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_KEY_TRUST_RID } }
// S-1-18-5
#define SID_KEY_PROPERTY_MFA { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_KEY_PROPERTY_MFA_RID } }
// S-1-18-6
#define SID_KEY_PROPERTY_ATTESTATION { SID_REVISION, SECURITY_AUTHENTICATION_AUTHORITY_RID_COUNT, SECURITY_AUTHENTICATION_AUTHORITY, { SECURITY_AUTHENTICATION_KEY_PROPERTY_ATTESTATION_RID } }

#pragma endregion
